export type MenuItem = { name: string; price: number };
export type MenuCategory = { id: string; title: string; icon: string; items: MenuItem[] };

export const menuCategories: MenuCategory[] = [
  {
    id: "nv-main",
    title: "Non-Veg Main Course",
    icon: "🍛",
    items: [
      { name: "Anda Masala", price: 230 },
      { name: "Anda Bhurji", price: 220 },
      { name: "Andhra Chicken Curry (Bone)", price: 330 },
      { name: "Andhra Chicken Curry (Boneless)", price: 360 },
      { name: "Chicken Fry", price: 340 },
      { name: "Butter Chicken Curry", price: 360 },
      { name: "Kadai Chicken Curry", price: 350 },
      { name: "Kaju Chicken Curry", price: 370 },
      { name: "Rayalaseema Chicken Curry", price: 350 },
      { name: "Patiala Chicken Curry", price: 370 },
      { name: "Mughlai Chicken Curry", price: 360 },
      { name: "Mutton Fry", price: 450 },
      { name: "Mutton Curry", price: 450 },
      { name: "Mutton Ghee Roast", price: 470 },
      { name: "Prawns Curry", price: 450 },
      { name: "Prawns Fry", price: 450 },
      { name: "Fish Curry", price: 420 },
      { name: "Boneless Fish Fry", price: 420 },
    ],
  },
  {
    id: "nv-starters",
    title: "Non-Veg Starters",
    icon: "🍗",
    items: [
      { name: "Egg 65 / Chilli", price: 280 },
      { name: "Chicken 65 / Chilli / Manchurian", price: 370 },
      { name: "Chicken Majestic / 555", price: 370 },
      { name: "Chicken Lollipop", price: 370 },
      { name: "Chicken Drumsticks", price: 370 },
      { name: "Cracker Lollipop", price: 380 },
      { name: "Chicken Wings", price: 370 },
      { name: "Chicken Joints", price: 370 },
      { name: "Lemon Chicken", price: 370 },
      { name: "Dragon Chicken", price: 370 },
      { name: "Butter Garlic Chicken", price: 380 },
      { name: "Pepper Chicken", price: 370 },
      { name: "Kaju Chicken Dry", price: 390 },
      { name: "RR Chicken", price: 370 },
      { name: "Crunchy Chicken", price: 370 },
      { name: "Napoleon Chicken", price: 370 },
      { name: "Cream of Fried Chicken", price: 380 },
      { name: "Dilruba Chicken", price: 390 },
      { name: "Kamju Pitta (4 Pieces)", price: 399 },
    ],
  },
  {
    id: "veg-tandoori",
    title: "Veg Tandoori",
    icon: "🔥",
    items: [
      { name: "Paneer Tikka", price: 370 },
      { name: "Malai Paneer Tikka", price: 370 },
      { name: "Hariyali Paneer Tikka", price: 370 },
      { name: "Tandoori Gobi", price: 350 },
      { name: "Tandoori Broccoli", price: 360 },
    ],
  },
  {
    id: "nv-tandoori",
    title: "Non-Veg Tandoori",
    icon: "🔥",
    items: [
      { name: "Chicken Tandoori", price: 350 },
      { name: "Chicken Tikka", price: 370 },
      { name: "Gulab Chicken Kebab", price: 370 },
      { name: "Banjara Chicken Kebab", price: 370 },
      { name: "Tangdi Kebab", price: 370 },
      { name: "Hariyali Chicken Tikka", price: 370 },
      { name: "Kaju Malai Chicken Tikka", price: 380 },
      { name: "Fish Tikka", price: 399 },
      { name: "Apollo Full Fish", price: 449 },
    ],
  },
  {
    id: "nv-biryani",
    title: "Non-Veg Biryanis",
    icon: "🍚",
    items: [
      { name: "Biryani Rice", price: 220 },
      { name: "Egg Biryani", price: 290 },
      { name: "Chicken Dum Biryani", price: 330 },
      { name: "Chicken Fry Biryani", price: 360 },
      { name: "Boneless Chicken Biryani", price: 380 },
      { name: "Rose Cafe Special Biryani", price: 399 },
      { name: "Chicken Joint/Wings/Lollipop Biryani", price: 399 },
      { name: "Mughlai Chicken Biryani", price: 399 },
      { name: "Chicken Tikka Biryani", price: 399 },
      { name: "Chicken Tandoori Biryani", price: 399 },
      { name: "Kaju Chicken Biryani", price: 399 },
      { name: "Potlam Biryani", price: 399 },
      { name: "Fire Biryani", price: 399 },
      { name: "Mutton Fry Biryani", price: 480 },
      { name: "Mutton Keema Biryani", price: 490 },
      { name: "Special Mutton Biryani", price: 499 },
      { name: "Mutton Nalli Gosht Biryani", price: 490 },
      { name: "Mutton Ghee Roast Biryani", price: 499 },
      { name: "Mutton Dum Biryani", price: 480 },
    ],
  },
  {
    id: "veg-biryani",
    title: "Veg Biryanis",
    icon: "🌿",
    items: [
      { name: "Veg Dum Biryani", price: 290 },
      { name: "Special Veg Dum Biryani", price: 340 },
      { name: "Kaju Paneer Biryani", price: 360 },
      { name: "Shahi Paneer Biryani", price: 350 },
      { name: "Shahi Mushroom Biryani", price: 330 },
      { name: "Kaju Mushroom Biryani", price: 360 },
    ],
  },
  {
    id: "veg-main",
    title: "Veg Main Course",
    icon: "🥘",
    items: [
      { name: "Mixed Veg Curry", price: 270 },
      { name: "Kadai Veg Curry", price: 280 },
      { name: "Veg Kofta", price: 270 },
      { name: "Kaju Tomato Curry", price: 330 },
      { name: "Kaju Masala", price: 350 },
      { name: "Mushroom Masala", price: 299 },
      { name: "Kadai Mushroom", price: 299 },
      { name: "Kaju Mushroom Masala", price: 330 },
      { name: "Kaju Paneer Curry", price: 350 },
      { name: "Kadai Paneer", price: 330 },
      { name: "Paneer Tikka Masala", price: 330 },
      { name: "Paneer Pasanda", price: 350 },
    ],
  },
  {
    id: "seafood",
    title: "Seafood",
    icon: "🦐",
    items: [
      { name: "Apollo Fish", price: 420 },
      { name: "Chilli Fish", price: 420 },
      { name: "Fish 65", price: 420 },
      { name: "Hot Pepper Fish", price: 420 },
      { name: "Loose Prawns", price: 420 },
      { name: "Prawns 65 / Chilli / Manchurian", price: 420 },
      { name: "Butter Garlic Prawns", price: 420 },
      { name: "Pepper Prawns", price: 420 },
      { name: "Thread Prawns", price: 440 },
    ],
  },
  {
    id: "rice",
    title: "Rice",
    icon: "🍚",
    items: [
      { name: "Ghee Rice", price: 199 },
      { name: "Jeera Rice", price: 250 },
      { name: "Veg Fried Rice", price: 250 },
      { name: "Paneer Fried Rice", price: 299 },
      { name: "Mushroom Fried Rice", price: 290 },
      { name: "Baby Corn Fried Rice", price: 290 },
      { name: "Kaju Fried Rice", price: 299 },
      { name: "Schezwan Veg Fried Rice", price: 280 },
      { name: "Double Egg Fried Rice", price: 299 },
      { name: "Chicken Fried Rice", price: 320 },
      { name: "Special Chicken Fried Rice", price: 360 },
      { name: "Schezwan Chicken Fried Rice", price: 330 },
    ],
  },
  {
    id: "continental",
    title: "Continental",
    icon: "🥗",
    items: [
      { name: "Toasted Green Veg Salad", price: 199 },
      { name: "Russian Veg Salad", price: 199 },
      { name: "Egg & Lettuce Salad", price: 229 },
      { name: "Mexican Veg Salad", price: 199 },
      { name: "Mexican Non-Veg Salad", price: 249 },
      { name: "Chicken Hawaiian Salad", price: 249 },
      { name: "Salted French Fries", price: 109 },
      { name: "Peri Peri French Fries", price: 129 },
      { name: "Cheese French Fries", price: 149 },
      { name: "Alfredo Pasta", price: 249 },
      { name: "Spaghetti Aglio e Olio", price: 249 },
      { name: "Grilled Vegetables with Butter Rice", price: 299 },
      { name: "Grilled Chicken with Butter Rice", price: 349 },
    ],
  },
  {
    id: "mocktails",
    title: "Mocktails",
    icon: "🍹",
    items: [
      { name: "Fresh Lime Soda (Sweet / Salt)", price: 70 },
      { name: "Orange Sunrise", price: 140 },
      { name: "Iced Tea", price: 120 },
      { name: "Blue Lagoon", price: 140 },
      { name: "Sunset Watermelon", price: 140 },
      { name: "Rose Pink Soda", price: 130 },
      { name: "Cranberry Mocktail", price: 140 },
      { name: "Strawberry Mocktail", price: 140 },
      { name: "Saudi Champagne", price: 170 },
    ],
  },
  {
    id: "milkshakes",
    title: "Milkshakes",
    icon: "🥤",
    items: [
      { name: "Butterscotch", price: 160 },
      { name: "Dry Fruits", price: 180 },
      { name: "Caramel Nuts", price: 170 },
      { name: "Almond Crunch", price: 170 },
      { name: "Chocolate", price: 199 },
      { name: "Strawberry", price: 199 },
      { name: "Vanilla", price: 160 },
      { name: "Black Currant", price: 199 },
    ],
  },
  {
    id: "icecreams",
    title: "Ice Creams",
    icon: "🍨",
    items: [
      { name: "Butterscotch", price: 160 },
      { name: "Dry Fruits", price: 180 },
      { name: "Caramel Nuts", price: 170 },
      { name: "Almond Crunch", price: 170 },
      { name: "Chocolate", price: 150 },
      { name: "Strawberry", price: 150 },
      { name: "Vanilla", price: 140 },
      { name: "Black Currant", price: 170 },
      { name: "Honeymoon Delight", price: 180 },
    ],
  },
  {
    id: "beverages",
    title: "Beverages",
    icon: "🥛",
    items: [
      { name: "Water Bottle (500 ml)", price: 15 },
      { name: "Cool Drink (250 ml)", price: 20 },
      { name: "Lassi", price: 70 },
      { name: "Buttermilk", price: 50 },
    ],
  },
  {
    id: "breads",
    title: "Breads",
    icon: "🫓",
    items: [
      { name: "Pulka", price: 20 },
      { name: "Butter Pulka", price: 25 },
      { name: "Roti", price: 50 },
      { name: "Butter Roti", price: 55 },
      { name: "Plain Naan", price: 55 },
      { name: "Butter Naan", price: 65 },
      { name: "Butter Garlic Naan", price: 80 },
      { name: "Paneer Kulcha", price: 90 },
      { name: "Masala Kulcha", price: 90 },
      { name: "Aloo Paratha", price: 90 },
      { name: "Paneer Paratha", price: 99 },
    ],
  },
];